# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoundSight' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SoundSight

  target 'SoundSightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoundSightUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
